<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Brief;
use App\Services\AnswerGenerator;
use App\Services\Facts;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class AnswerController extends Controller
{
    /**
     * Open the page for a question: an existing answer is reused, a new one is generated by the page.
     */
    public function store(Request $request): RedirectResponse
    {
        $data = $request->validate([
            'question' => ['required', 'string', 'min:8', 'max:300'],
            'locale' => ['required', 'in:en,ar'],
        ]);

        // Answer in the language the question is written in, whichever page it was asked from.
        $locale = preg_match('/\p{Arabic}/u', $data['question']) ? 'ar' : 'en';

        return to_route('answers.show', Answer::forQuestion($data['question'], $locale));
    }

    /**
     * Generate a pending answer. Called by the answer page, like brief generation.
     */
    public function generate(Answer $answer, AnswerGenerator $generator): JsonResponse
    {
        if (BriefController::claim($answer)) {
            // The edge proxy may time out (~20s) before the model finishes; keep going, the page polls.
            ignore_user_abort(true);
            set_time_limit(BriefController::STALE_AFTER);
            $answer->generate($generator);
        }

        return response()->json(['status' => $answer->fresh()->status]);
    }

    public function show(Answer $answer, Facts $facts): Response
    {
        $status = $answer->status === Brief::GENERATING && $answer->updated_at->diffInSeconds() > BriefController::STALE_AFTER
            ? Brief::FAILED
            : $answer->status;

        // Once answered, only the cleaned question (no names, numbers or injected claims) is ever shown or sent.
        $question = $answer->content['public_question'] ?? $answer->question;

        return Inertia::render('answer/Show', [
            'locale' => $answer->locale,
            'answer' => [
                'id' => $answer->public_id,
                'question' => $question,
                'locale' => $answer->locale,
                'status' => $status,
                'content' => $answer->content,
                'sources' => $facts->citedSources($answer->content),
                'asked_count' => $answer->asked_count,
                'updated_at' => $answer->updated_at->toIso8601String(),
            ],
        ])->withViewData(['meta' => [
            // Server-rendered, so link previews (WhatsApp, LinkedIn) and crawlers see them without JavaScript.
            'title' => $question,
            'description' => $answer->content['short_answer']['text'] ?? null,
            'indexable' => $status === Brief::READY && ($answer->content['publishable'] ?? false),
        ]]);
    }
}
